### ISSUE TITLE
Use AWS FarGate to run container

### ISSUE THREAD

**Issue by mjkrause** [HumanCellAtlas/data-portal-summary-stats#12]
For a first pass I use the Amazon Elastic Container Registry (ECR).
- [x] get login authentication for Docker client
- [x] in the HCA repository create namespace `data-portal-summary-stats`
- [x] push container to the repo 

ECS Fargate
- [x] create task definition
- [x] configure service and cluster
- [x] run container on ECS/Fargate
- [x] schedule container runs

- [x] add Terraform script to provision parameters and run tasks
- [ ] update README

**Comment by hannes-ucsc** [comment]
To clarify, the resolution of this ticket should include the creation of a Dockerfile and Terraform configuration and committing them to this repo. IOW, any developer should—after checking out this repo—be able to run 

- `docker build` to create the image
- `docker push` to push it to ECR
- `terraform apply` to create the task definition, the ECS cluster and the CloudWatch event rule that triggers the container.

If any special steps are required in between, like `docker login` for ECR those should be documented in a README.
