### ISSUE TITLE
Request matrix from project

### ISSUE THREAD

**Issue by theathorn** [HumanCellAtlas/data-portal-summary-stats#2]
* get list of projects using Azul's /repository/projects endpoint or the HCA matrix-service API
* check if matrix file exists for project, if so, requests matrix in loom format (that persists the matrix on S3 and returns a (signed?)URL to it)
* return list of all matrix URLs S3

**Comment by mjkrause** [comment]
In the current implementation project IDs (within a given deployment environment) are pulled from the HCA matrix service. This is the most pragmatic approach (i.e., even if there are more project IDs in Azul that information is insignificant as we can only process matrices which can be downloaded from the matrix service.
In addition to obtaining matrices from the matrix service, the code can alternatively use _canned_ matrices from S3 (per deployment environment).
