### ISSUE TITLE
Separate by library construction method

### ISSUE THREAD

**Issue by mjkrause** [HumanCellAtlas/data-portal-summary-stats#21]
Some of the projects return a matrix containing a mix of data generated with more than one library construction method (e.g., project _Reconstructing the human first trimester fetal-maternal interface using single cell transcriptomics_ consists of a mix of 10x and smartseq2). 
Write a method that separates the matrix data into independent entities such that they can be analyzed separately.  This is important as we found that parameter `min_gene_count` affects the cell count differential, depending on the library construction method used.
Criterion for done should be that the cell count (once processing is complete) of a given matrix should return the same value, independent of the underlying library construction method.

**Comment by noah-aviel-dove** [comment]
https://github.com/HumanCellAtlas/data-portal-summary-stats/issues/19#issuecomment-540687878

**Comment by theathorn** [comment]
Estimate includes code refactoring.
