### ISSUE TITLE
Create Docker image container to generate summary figures

### ISSUE THREAD

**Issue by theathorn** [HumanCellAtlas/data-portal-summary-stats#5]
I raised this issue after the idea of accomplishing the generation of the summary figures using an AWS Lambda has been abandoned, as described in #6. The thinking following a discussion with @hannes-ucsc is that any alternative approach of addressing this problem would necessitate running the code inside a container.

**Comment by mjkrause** [comment]
The code runs successfully in a docker container and has been demoed to the team on 2019-08-13, and the code (including a blacklist switch) has been merged into branch `develop`. I therefore close this ticket. I opened a new ticket (#11), which describes the creation of the missing violin plots.
