### ISSUE TITLE
Use microservice to invoke summary stats functionality

### ISSUE THREAD

**Issue by theathorn** [HumanCellAtlas/data-portal-summary-stats#6]
Summary statistics should be computed per project once a day. Discuss with @hannes-ucsc whether this should be part of Azul's webservice Lambda, or whether it should run in a separate service.

**Comment by theathorn** [comment]
From @mkrause:
@hannes-ucsc and I found that the deployment package size exceeds the limit allowed for an AWS Lambda. The main reason is the size of large libraries in that package, such as scipy, scanpy, pandas and numpy, all of which are installed when scanpy is installed. The uncompressed size of the deployment package was > 250 MB, exceeding the limit.
That observation makes the approach of using an AWS Lambda to post summary figures to S3 not viable.

**Comment by mjkrause** [comment]
The current implementation is to run the code in a docker container (see #5 for details). Using an AWS Lambda is not a viable solution to address this problem. I therefore close this ticket.
