### ISSUE TITLE
Create class to compute summary statistics from matrix

### ISSUE THREAD

**Issue by theathorn** [HumanCellAtlas/data-portal-summary-stats#7]
* get list of URLs of matrix loom files persisted on S3
* download each matrix loom file
* Explore utility of package loompy to iterate over (or scan) columns / rows of matrix in loom file
    * create genes-by-cells matrix in memory
    * this may not be necessary if we can use loompy's `map()` or `scan()` methods, in combination with numpy's summary statistics methods
    * explore whether matrix files from different library construction methods require differential processing
* Utilize package ScanPy to create plots of relevant values
* Upload and persist on S3 (for later use by portal team to display it)

**Comment by mjkrause** [comment]
Functionality described in this ticket has been implemented and demoed. Creation of violin plots is now separate from this ticket (#11) as it is not as straight-forward as initially thought.
